AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  numberemailer-webhook

  Sample SAM Template for numberemailer-webhook

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 12
  Api:
    Cors:
      AllowMethods: "'GET,HEAD,OPTIONS,PUT,POST'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Parameters:
  ExecEnv:
    Type: String
    AllowedValues:
      - local
      - dev
      - stage
      - prod
    Default: prod
  DBUrl:
    Type: String
  BucketName:
    Type: String


Resources:
  SendGridWebHookFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: rest_api/
      Handler: app.app
      Runtime: python3.8
      Environment:
        Variables:
          EXEC_ENV: !Ref ExecEnv
          DB_URL: !Ref DBUrl
          BUCKET_NAME: !Ref BucketName
      Events:
        SendGridWebHookApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /events/
            Method: POST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SendGridWebHookApi:
    Description: "API Gateway endpoint URL for Prod stage for SendGrid Webhook function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/events/"
  SendGridWebHookFunction:
    Description: "SendGrid Webhook Lambda Function ARN"
    Value: !GetAtt SendGridWebHookFunction.Arn
  SendGridWebHookFunctionIamRole:
    Description: "Implicit IAM Role created for SendGrid Webhook function"
    Value: !GetAtt SendGridWebHookFunctionRole.Arn
